####################################################
#                 HOME ASSISTANT                   #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.14

####################################################
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
cloud: !include cloud.yaml
frontend:
  themes: !include_dir_merge_named themes/
ios: !include ios.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/

####################################################
#                     GENERAL                      #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml
  resources:
    #https://github.com/custom-cards/stack-in-card
    - url: /local/stack-in-card.js
      type: module
    #https://github.com/maykar/custom-header
    - url: /local/custom-header.js?v=0.0.1
      type: module

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://www.home-assistant.io/integrations/stream/
stream:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/integrations/system_health/
system_health:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate

#https://www.home-assistant.io/integrations/zone/
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 750

####################################################
#                     CAMERA                       #
####################################################

#https://www.home-assistant.io/integrations/generic_ip_camera/
camera:
  - platform: generic
    name: Nursery Camera
    stream_source: !secret stream_source
    still_image_url: !secret still_image_url

####################################################
#                     COVER                        #
####################################################

#https://www.home-assistant.io/components/opengarage/
cover:
  platform: opengarage
  covers:
      garage:
        host: 192.168.1.18
        device_key: !secret device_key
        name: Garage Door

####################################################
#                 INPUT BOOLEAN                    #
####################################################

#https://home-assistant.io/components/input_boolean/
input_boolean:
  vacation:
    name: Vacation Mode
    initial: off
  guest:
    name: Guest Mode
    initial: off
  feeddog:
    name: feeddog
    initial: off
  doorbelllight:
    name: doorbelllight
    initial: off

####################################################
#                     LIGHT                        #
####################################################

#https://www.home-assistant.io/components/light.group/
light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.yeelight3
      - light.yeelight4

  - platform: group
    name: Front Lights
    entities:
      - light.yeelight1
      - light.kuled6

  - platform: group
    name: Basement Lights
    entities:
      - light.zooz_zen27_s2_dimmer_wall_switch_level
      - light.zooz_zen27_s2_dimmer_wall_switch_level_2
      - light.zooz_zen27_s2_dimmer_wall_switch_level_3

  - platform: switch
    name: basic1
    entity_id: switch.basic1

  - platform: switch
    name: kuled1
    entity_id: switch.kuled1

  - platform: switch
    name: kuled2
    entity_id: switch.kuled2

  - platform: switch
    name: kuled3
    entity_id: switch.kuled3

  - platform: switch
    name: kuled4
    entity_id: switch.kuled4

  - platform: switch
    name: kuled5
    entity_id: switch.kuled5

  - platform: switch
    name: kuled6
    entity_id: switch.kuled6

  - platform: flux_led
    devices:
      192.168.1.4:
        name: Mikey's Bed Lights
        mode: "rgbw"
      192.168.1.42:
        name: LED Strip Light2
        mode: "rgbw"

####################################################
#                MEDIA PLAYER                      #
####################################################

#https://www.home-assistant.io/integrations/yamaha_musiccast/
media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.3

####################################################
#                NOTIFICATIONS                     #
####################################################

#https://home-assistant.io/components/notify.smtp/
notify:
  - platform: smtp
    name: Home_Assistant
    server: smtp.gmail.com
    port: 587
    sender: !secret notification_sender
    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient: !secret notification_recipient

  - platform: smtp
    name: Amy
    server: smtp.gmail.com
    port: 587
    sender: !secret notification_sender
    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient: !secret notification_amy

####################################################
#                   SAMSUNG TV                     #
####################################################

#https://www.home-assistant.io/integrations/samsungtv/
samsungtv:
  - host: 192.168.1.9
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "8c:79:f5:68:4b:7b"

####################################################
#               UTILITY METER                      #
####################################################

#https://home-assistant.io/components/utility_meter/
utility_meter:
  daily_energy:
    source: sensor.aeon_labs_dsb28_home_energy_meter_2nd_edition_energy
    cycle: daily

  monthly_energy:
    source: sensor.aeon_labs_dsb28_home_energy_meter_2nd_edition_energy
    cycle: monthly

####################################################
#                   WEATHER                        #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

####################################################
#                     YEELIGHTS                    #
####################################################

#https://home-assistant.io/components/light.yeelight/
yeelight:
  devices:
    192.168.1.10:
      name: Yeelight1
    192.168.1.11:
      name: Yeelight2
    192.168.1.12:
      name: Yeelight3
    192.168.1.26:
      name: Yeelight4
    192.168.1.28:
      name: Yeelight5

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################