#########################################################
#                                                       #
#                 LEAVING HOME                          #
#                                                       #
#########################################################

- alias: Leaving Home
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.adam
      from: 'home'
    - platform: state
      entity_id: person.amy
      from: 'home'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
      - condition: template
        value_template: "{{ states('person.amy') != 'home' }}"
      - condition: template  
        value_template: "{{ states('input_boolean.guest') != 'on' }}"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.kuled1
        - switch.kuled2
        - switch.kuled3
        - switch.kuled4
        - switch.basic1
    - service: light.turn_off
      entity_id:
        - light.zooz_zen27_s2_dimmer_wall_switch_level
        - light.zooz_zen27_s2_dimmer_wall_switch_level_2
        - light.zooz_zen27_s2_dimmer_wall_switch_level_3
        - light.zooz_zen27_s2_dimmer_wall_switch_level_4
        - light.yeelight3
        - light.yeelight4

########################################################
#                                                      #
#             END OF CONFIGURATION FILE                #
#                                                      #
########################################################
